### ISSUE TITLE
Requesting clarification re proposal pull request

### ISSUE THREAD

**Issue by rnicholus** [JSFoundation/TAC#18]
In the [Project-Lifecycle.md document](https://github.com/JSFoundation/TAC/blob/master/Project-Lifecycle.md#applying-to-join), it is stated that:

>Each proposal should be sent as a pull request to this repository in the Applications directory.

However, I do not see such a directory in this repository. Has something changed, or am I misunderstanding the directions?

**Comment by kborchers** [comment]
Thank you for reaching out. That directory is currently empty so it will not show in the GitHub UI. If you clone the repo it should be there but if not, just create an "Applications" directory and create your document in there.

**Comment by rnicholus** [comment]
Thanks for the clarification Kris.
