### ISSUE TITLE
https://try.jquery.com/ is down

### ISSUE THREAD

**Issue by IdeaHunter** [JSFoundation/TAC#30]
When trying to access site getting following error:

> Error 1014 Ray ID: 42412abacaf275f4 • 2018-06-01 10:58:45 UTC
> CNAME Cross-User Banned
> What happened?
> You've requested a page on a website that is part of the Cloudflare network. The host is configured as a CNAME across accounts on Cloudflare, which is prohibited by security policy.
> 
> What can I do?
> If you are interested in learning more about Cloudflare, please visit our website.
> 
> Cloudflare Ray ID: 42412abacaf275f4 • Your IP: 83.221.210.53 • Performance & security by Cloudflare

Not sure if this right place to report, if its not - please point me out right one 😸

**Comment by dmethvin** [comment]
See https://github.com/jquery/jquery.com/issues/176
