### ISSUE TITLE
JSFoundation - Call for Code?

### ISSUE THREAD

**Issue by rubys** [JSFoundation/TAC#31]
IBM is sponsoring the [Call For Code](https://callforcode.org) (along with a number of other organizations like the American Red Cross) with the first challenge being focused on bringing people together to help build solutions for disaster preparedness.

The JSFoundation is [listed](https://callforcode.org/ecosystem/) as a Program Affiliate.

If there is interest we (@mhdawson and myself) could arrange an intro session for the JSFoundation community members and then help to connect those who are interested in participating.

**Comment by jorydotcom** [comment]
@rubys thank you for letting us know - I hope the event was really successful and that we can drive more interest from the new $foundation projects next year!
