### ISSUE TITLE
JSF End-of-Year Project Meeting

### ISSUE THREAD

**Issue by jorydotcom** [JSFoundation/TAC#34]
**Date:** 2018.12.04
**Time:** 12:00-1:00 EST (UTC 5:00 p.m.)
**Meeting Link:** 
https://zoom.us/j/6968247504
One tap mobile
+16465588656,,6968247504# US (New York)
+16699006833,,6968247504# US (San Jose)

Dial by your location
        +1 646 558 8656 US (New York)
        +1 669 900 6833 US (San Jose)
        +1 855 880 1246 US Toll-free
        +1 877 369 0926 US Toll-free
Meeting ID: 696 824 7504
Find your local number: https://zoom.us/u/acAaicET2E

**[Slide Deck](https://docs.google.com/presentation/d/1BuEEWXLaA8SumYnj9qADJuNo3EKv4bfwktV7nJMwacY/edit?usp=sharing)**

* **Merge Status/updates & questions**
  * Overview of Work & Timeline
  * Key implications for JSF projects
* **Standards Activities - TC39 & W3C**
* **Recognition Program Update**
* **Open Discussion - ideas? concerns? questions? needs?**

**Comment by zherczeg** [comment]
Hi @jorydotcom . May I ask when the link for the meeting will be available?

**Comment by jorydotcom** [comment]
@zherczeg I'm borrowing someone's Zoom account so there's no issue if we go over time, but he hasn't got it set properly just yet so we can use it without issue. I will post that link just as soon as it appears to be working right!
