### ISSUE TITLE
Create High Level Technical Org Structure

### ISSUE THREAD

**Issue by kborchers** [JSFoundation/TAC#4]
This structure should define the different types of organizational groups, committees, etc with a description that maps directly to how each piece of the structure maps to the goals defined in #3

**Comment by jzaefferer** [comment]
Let's answer the question @nzakas posted in #4:

> Then it sounds like what we're looking for is a "project health committee" rather than anything else. It also sounds like it would be important for whomever is on this committee to actually not be actively working on the project to provide more of the community perspective?

I suggest keeping it simple has he suggested, instead of trying to come up with multiple groups from the start.

**Comment by nzakas** [comment]
Yeah, the more I dug into the goals, the more I thought having a single project health committee makes the most sense. If they are really just doing spot checks and only deeply engage when things have gone off the rails, I don't think having multiple groups is necessary *right now*. It seems like we'd get the most of this effort by having one group get really comfortable with the duties and practices rather than trying to spin up 5-6 and expect them all to figure it out (it also prevents the now-seemingly-unimportant grouping of projects together).

This doesn't preclude multiple committees in the future, of course.

**Comment by kborchers** [comment]
This specific issue has been resolved by 6dbb14cc936fb8961d3176c29f1247e057c64ccc though the exact committees, working groups, collaboration boards, etc under the TAC will likely form and evolve over time as the TAC membership is filled and begins updating and adjusting policies based on project feedback.

**Comment by rxaviers** [comment]
@kborchers by looking the commit you referenced (6dbb14c), it's not clear to me how it resolves this issue, specially how it solves the goals defined in #3 plus the comments raised is this issue. It would be great if it could be clarified. Thanks

**Comment by kborchers** [comment]
@rxaviers I believe this is all mostly outlined in the [TAC charter](https://github.com/JSFoundation/TAC/blob/master/TAC-Charter.md) which that commit was the result of ratification of that charter by the board. The goals set in #3 are intended to be met as follows:

1. **Separate the business aspects from the technical aspects of the Foundation.**
   By creating a TAC, this separates technical governance from business governance. Obviously, the TAC itself is still being formed but the creation of a separate body for technical guidance of the Foundation meets this goal of separation.
2. **Establish a set of best practices for sustaining open source projects.**
   These base policies are set both within the TAC charter as well as the base policies in that repo. These items can and will evolve over time but they have been established.
3. **Separate policy review from writing code and running a project.**
   This is accomplished via CBs and the TAC as defined in the TAC charter.
4. **Have an independent group acting as an advocate for the project community.**
   Again, the TAC accomplishes this as it is not tied to a single project but rather has a higher level view of the projects and the ecosystem and can provide input and feedback to the projects on opportunities and threats seen by the community.
5. **Tailor involvement with the Foundation to fit project needs.**
   This is accomplished by the creation of the idea of At-Large projects which was based directly on the feedback from the jQuery Foundation projects during the creation of this organization. If a project feels it is stable or would not care to participate in the greater technical structure of the JS Foundation, they can fall into the At-Large project group.
